name: Lint

on: [push]

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: stefanoeb/eslint-action@1.0.2
      - uses: iCrawl/action-eslint@v1
        with:
          reporter: github-check
          node-version: '16.16.0'
          files: src/
