on:
  push:
    tags:
      - 'v*' 

name: Create Release

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
    - name: Node
      uses: actions/setup-node@v2
      with:
        node-version: "16.16.0"
    - name: Check lint and ts
      uses: actions/checkout@v2
    - run: yarn
    - run: yarn lint
    - run: yarn tsc
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env: 
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
      with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            Changes in this Release
            - First Change
            - Second Change
          draft: false
          prerelease: false
     
